listen_interface: #监听的接口
  - lo0
firewall_program: iptables
firewall_rule_name: yonezawa
time_out: 3600 #全局超时时间
webhook_url: "http://127.0.0.1:2333/?log=[{time}]允许{address}访问{ports}端口"
webhook_method: "GET"
webhook_data: "[{time}]允许{address}访问{ports}端口"
webhook_headers:
  - "nya: nya"
hot_update: "" #热更新
auto_reload: false #自动重载配置文件
auto_reload_delay: 60 #自动重载延迟
open_ports: "80,22" #默认开放端口
rules:
  - size: 56 #规则匹配的数据包大小
    time_out: 3600 #单条规则超时时间
    allow_ports: 1:65535 #允许的端口
    pattern: 0xff #规则匹配的数据包内容